name: velocirrus-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit
  - geopandas
  - cartopy
  - pydeck
  - pandas
  - numpy
  - pip
  - pip:
    - pycontrails[complete]
    - traffic
    - google-auth
